format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$package\
$c\
$golang\
$haskell\
$java\
$kotlin\
$python\
$rlang\
$rust\
$swift\
$fill\
$jobs $memory_usage $cmd_duration $time\
$line_break\
$character"""

[fill]
symbol = " "

[directory]
style = "blue"
read_only = " "
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "../"

[package]
format = "[$symbol$version]($style) "

[c]
format = "[$symbol($version(-$name))]($style) "

[golang]
format = "[$symbol($version)]($style) "

[haskell]
format = "[$symbol($version)]($style) "

[java]
format = "[${symbol}(${version})]($style) "

[kotlin]
format = "[$symbol($version)]($style) "

[python]
format = "[${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\))]($style) "

[rlang]
format = "[$symbol($version)]($style) "

[rust]
format = "[$symbol($version)]($style) "

[swift]
format = "[$symbol($version)]($style) "

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bright-black"

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[memory_usage]
disabled = false
threshold = 50
format = "$symbol[$ram( | $swap)]($style) "

[time]
disabled = false
style = "bold white"
time_format = "%H:%M"
format = "[$time]($style)"

[username]
disabled = false
show_always = false
format = "[$user]($style)@"

[hostname]
disabled = false
ssh_only = true
format = "[$ssh_symbol$hostname]($style) "
